# Generated by Django 5.1.7 on 2025-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantitative_indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=20)),
                ('value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'quantitative_indicators',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
