# Generated by Django 5.1.7 on 2025-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quantitative_indicator_alter_course_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantitative_indicator1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=20)),
                ('value', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quantitative_indicators1',
            },
        ),
    ]
