# Generated by Django 5.1.7 on 2025-04-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quantitative_indicator1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantitative_indicator1',
            old_name='indicator',
            new_name='indicator1',
        ),
        migrations.RenameField(
            model_name='quantitative_indicator1',
            old_name='value',
            new_name='value1',
        ),
    ]
