# Generated by Django 5.1.7 on 2025-04-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quantitative_indicator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantitative_indicator',
        ),
    ]
