# Generated by Django 5.1.7 on 2025-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
