# Generated by Django 5.1.7 on 2025-04-09 09:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_company_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('reservation', ckeditor.fields.RichTextField()),
                ('opening_hours', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
