# Generated by Django 5.1.7 on 2025-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='reservation',
            new_name='for_reservation',
        ),
    ]
